.github/workflows/ci.yml
.github/workflows/release.yml
Makefile

First Beta Release

---

.github/workflows/release.yml

ci: Remove force version (use tag instead)

---

docs/Configuration.md
docs/Quickstart.md
docs/index.json

doc: Add documentation + quickstart

---

config/lts/config.go
examples/lts/group.yaml
examples/lts/topic.yaml
scripts/cli.py

feat(lts): add support and examples of Log Tank Service

---

.github/workflows/release.yml

Add env variables to release Workflow

ci: add GO ENV to release workflow

---

apis/waf/v1beta1/zz_domain_types.go
apis/waf/v1beta1/zz_rulealarmmasking_types.go
apis/waf/v1beta1/zz_ruleblacklist_types.go
apis/waf/v1beta1/zz_ruleccprotection_types.go
apis/waf/v1beta1/zz_ruledatamasking_types.go
apis/waf/v1beta1/zz_rulepreciseprotection_types.go
apis/waf/v1beta1/zz_rulewebtamperprotection_types.go
config/overrides.go
config/waf/config.go
examples/waf/certificate.yaml
examples/waf/dedicatedcertificate.yaml
examples/waf/dedicateddomain.yaml
examples/waf/dedicatedinstance.yaml
examples/waf/dedicatedpolicy.yaml
examples/waf/domain.yaml
examples/waf/policy.yaml
examples/waf/rulealarmmasking.yaml
examples/waf/ruleblacklist.yaml
examples/waf/ruleccprotection.yaml
examples/waf/ruledatamasking.yaml
examples/waf/rulepreciseprotection.yaml
examples/waf/rulewebtamperprotection.yaml
package/crds/waf.flexibleengine.upbound.io_domains.yaml
package/crds/waf.flexibleengine.upbound.io_rulealarmmaskings.yaml
package/crds/waf.flexibleengine.upbound.io_ruleblacklists.yaml
package/crds/waf.flexibleengine.upbound.io_ruleccprotections.yaml
package/crds/waf.flexibleengine.upbound.io_ruledatamaskings.yaml
package/crds/waf.flexibleengine.upbound.io_rulepreciseprotections.yaml
package/crds/waf.flexibleengine.upbound.io_rulewebtamperprotections.yaml

Feature waf

---

scripts/cli.py

feat(script): add support for SecretRef

---

config/dis/config.go
examples/dis/stream.yaml

feat(dis): add example stream

---

apis/dds/v1beta1/zz_databaserole_types.go
apis/dds/v1beta1/zz_generated.deepcopy.go
apis/dds/v1beta1/zz_generated.resolvers.go
config/dds/config.go
examples-generated/dds/databaserole.yaml
examples/dds/instance.yaml
examples/dds/instance_secret.yaml
package/crds/dds.flexibleengine.upbound.io_databaseroles.yaml

feat(dds): add example instance

---

apis/dli/v1beta1/zz_generated.deepcopy.go
apis/dli/v1beta1/zz_generated.resolvers.go
apis/dli/v1beta1/zz_sparkjob_types.go
apis/dli/v1beta1/zz_table_types.go
config/dli/config.go
config/external_name.go
examples-generated/dli/sparkjob.yaml
examples/dli/database.yaml
examples/dli/dlipackage.yaml
examples/dli/dlipackage.yaml.extra
examples/dli/flinksqljob.yaml
examples/dli/flinksqljob.yaml.extra
examples/dli/queue.yaml
examples/dli/sparkjob.yaml
package/crds/dli.flexibleengine.upbound.io_sparkjobs.yaml
scripts/cli.py

Feature dli

---

examples/eps/project.yaml

feat(eps): add example project

---

examples/kms/key.yaml

feat(kms): add example key

---

examples/tms/tags.yaml

feat(tms): add example tags

---

apis/evs/v1beta1/zz_blockstoragevolume_types.go
apis/evs/v1beta1/zz_generated.resolvers.go
config/evs/config.go
examples/evs/blockstoragevolume.yaml
package/crds/evs.flexibleengine.upbound.io_blockstoragevolumes.yaml

Added and tested example for EVS
I have:
```
NAME                                                                              READY   SYNCED   EXTERNAL-NAME                          AGE
blockstoragevolume.evs.flexibleengine.upbound.io/example-evs-blockstoragevolume   True    True     REDACTED   84s
```

feat(evs): add examples

---

apis/vbs/v1beta1/zz_backup_types.go
apis/vbs/v1beta1/zz_backuppolicy_types.go
apis/vbs/v1beta1/zz_generated.deepcopy.go
apis/vbs/v1beta1/zz_generated.resolvers.go
config/vbs/config.go
examples/evs/blockstoragevolume.yaml
examples/vbs/backup.yaml
examples/vbs/backuppolicy.yaml
list-tested.md
package/crds/vbs.flexibleengine.upbound.io_backuppolicies.yaml
package/crds/vbs.flexibleengine.upbound.io_backups.yaml

Added and tested all resources for VBS
I have:

Feature vbs

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/example_required.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/new_resource_request.yml
.github/PULL_REQUEST_TEMPLATE.md

Add some templates to improve issues and pull requests

chore(template): add github template for issue and PR

---

.gitmodules
Makefile

Add new submodule githook for checking automatically if commit msg respect conventional commit  
```
❯ git commit -m "chore: add git hook submodule"
✔ commit message
[main 0998285] chore: add git hook submodule
3 files changed, 5 insertions(+)
create mode 160000 githooks
```

chore: add git hook submodule

---

.github/ISSUE_TEMPLATE/example_required.yml
.github/ISSUE_TEMPLATE/new_resource_request.yml

chore(template): fix template issue  syntax

---

CONTRIBUTING.md
README.md

Add a clean Readme for the users and separate contributing guide for the contributors.

docs: clean readme and add contributing guide

---

apis/v1beta1/types.go
config/sdrs/config.go
package/crds/flexibleengine.upbound.io_providerconfigs.yaml

fix(provider): allow empty insecure parameter

---

.github/ISSUE_TEMPLATE/terraform_change.yml

Add issue template to help us to track disruptive changes on Terraform provider.

chore: add template to track change in provider

---

.github/ISSUE_TEMPLATE/terraform_change.yml

chore(issue_template): fix syntax

---

.github/ISSUE_TEMPLATE/terraform_change.yml

Add the information about the Terraform Provider release in the form.

chore(issue_template): terraform provider version

---

.github/ISSUE_TEMPLATE/example_required.yml
.github/ISSUE_TEMPLATE/new_resource_request.yml
.github/ISSUE_TEMPLATE/terraform_change.yml

Improve text in the form templates

chore(templates): improve text value

---

.github/ISSUE_TEMPLATE/terraform_change.yml

Remove checkboxes in Terraform Change template.
Add all informations about Terraform provider version in one textarea

chore(template): remove checkboxes

---

apis/dms/v1beta1/zz_generated.resolvers.go
apis/dms/v1beta1/zz_kafkatopic_types.go
apis/dms/v1beta1/zz_kafkauser_types.go
config/dms/config.go
config/overrides.go
examples/dms/kafkainstance.yaml
examples/dms/kafkainstance_secret.yaml
examples/dms/kafkatopic.yaml
examples/dms/kafkauser.yaml
examples/dms/kafkauser_secret.yaml
package/crds/dms.flexibleengine.upbound.io_kafkatopics.yaml
package/crds/dms.flexibleengine.upbound.io_kafkausers.yaml

Add DMS kafka instance example
Add secret password for manager and user
I have:
```
NAME                                                              READY   SYNCED   EXTERNAL-NAME                                                  AGE
kafkauser.dms.flexibleengine.upbound.io/example-dms-kafka-user1   True    True     0234322a-1349-4ce8-811c-ec08cf2f6a93/example-dms-kafka-user1   82s
NAME                                                               READY   SYNCED   EXTERNAL-NAME             AGE
kafkatopic.dms.flexibleengine.upbound.io/example-dms-kafka-topic   True    True     example-dms-kafka-topic   16m
NAME                                                                     READY   SYNCED   EXTERNAL-NAME                          AGE …
```

feat(dms): Add examples

---

config/groups.go
examples/dcs/instance.yaml
examples/dcs/instance_secret.yaml

Add DCS feature example
I have:
NAME                                                                READY   SYNCED   EXTERNAL-NAME                          AGE
instance.dcs.flexibleengine.upbound.io/example-dcs-redis-instance   True    True     9fbf29e3-bd28-4030-a7b5-b5fc1778e7b9   6h
NAME                                            READY   SYNCED   EXTERNAL-NAME                          AGE
vpc.vpc.flexibleengine.upbound.io/example-vpc   True    True     13532b25-8836-46d7-bc57-14ace2bd47df   7d11h
NAME                                                     READY   SYNCED   EXTERNAL-NAME                          AGE
vpcsubnet.vpc.flexibleengine.upbound.io/example-subnet   False   True     2e044c75-c21f-4bad-9c04-c85a431f536e   7d11h

feat(dcs): Add new resources dcs

---

apis/dedicatedelb/v1beta1/zz_member_types.go
apis/dedicatedelb/v1beta1/zz_monitor_types.go
apis/elb/v1beta1/zz_member_types.go
apis/elb/v1beta1/zz_monitor_types.go
config/overrides.go
package/crds/dedicatedelb.flexibleengine.upbound.io_members.yaml
package/crds/dedicatedelb.flexibleengine.upbound.io_monitors.yaml
package/crds/elb.flexibleengine.upbound.io_members.yaml
package/crds/elb.flexibleengine.upbound.io_monitors.yaml

Fixes #92 
I have:
```
NAME                                              READY   SYNCED   EXTERNAL-NAME                          AGE
pool.elb.flexibleengine.upbound.io/example-pool   True    True    REDACTED   14m
NAME                                                      READY   SYNCED   EXTERNAL-NAME                          AGE
listener.elb.flexibleengine.upbound.io/example-listener   True    True     REDACTED   14m
NAME                                                  READY   SYNCED   EXTERNAL-NAME   AGE
member.elb.flexibleengine.upbound.io/example-member   True   True     REDACTED   14m
NAME                                                    READY   SYNCED   EXTERNAL-NAME                          AGE
loadbalancer.elb.flexibleengine.upbound.io/example-lb   True    True     REDACTED …
```

fix(elb): local type in global override

---

apis/swr/v1beta1/zz_generated.deepcopy.go
apis/swr/v1beta1/zz_generated.resolvers.go
apis/swr/v1beta1/zz_organizationusers_types.go
apis/swr/v1beta1/zz_repositorysharing_types.go
config/swr/config.go
examples-generated/swr/organizationusers.yaml
examples/iam/user.yaml
examples/iam/user.yaml.extra
examples/iam/user.yaml.secret
examples/swr/organization.yaml
examples/swr/organizationusers.yaml
examples/swr/repository.yaml
examples/swr/repositorysharing.yaml
list-tested.md
package/crds/swr.flexibleengine.upbound.io_organizationusers.yaml
package/crds/swr.flexibleengine.upbound.io_repositorysharings.yaml

I have:
```
❯ k get managed
NAME                                        READY   SYNCED   EXTERNAL-NAME                      AGE
user.iam.flexibleengine.upbound.io/user-1   True    True     73c2a8be87844016b5a4cdc62d39255d   65m
NAME                                                                            READY   SYNCED   EXTERNAL-NAME   AGE
repositorysharing.swr.flexibleengine.upbound.io/example-swr-repositorysharing   True    True     OCB0005117      3m39s
NAME                                                                            READY   SYNCED   EXTERNAL-NAME              AGE
organizationusers.swr.flexibleengine.upbound.io/example-swr-organizationusers   True    True     example-swr-organization   46m
NAME                                                              READY …
```

feat(swr): add resources and examples

---

apis/netacl/v1beta1/zz_acl_types.go
apis/netacl/v1beta1/zz_generated.deepcopy.go
apis/netacl/v1beta1/zz_generated.resolvers.go
config/netacl/config.go
examples-generated/netacl/acl.yaml
examples/netacl/acl.yaml
examples/netacl/acl.yaml.extra
examples/netacl/aclrule.yaml
examples/netacl/aclrule.yaml.extra
package/crds/netacl.flexibleengine.upbound.io_acls.yaml

Add Network ACL example 
I have:
```
NAME                                                      READY   SYNCED   EXTERNAL-NAME                          AGE
acl.netacl.flexibleengine.upbound.io/example-netacl-acl   True    True     ef394592-34fa-4df1-b2ae-91eaae90f503   16m
NAME                                                            READY   SYNCED   EXTERNAL-NAME                          AGE
aclrule.netacl.flexibleengine.upbound.io/example-netacl-rule    True    True     512ef1fd-f26f-4147-bd16-1bab4b3e4eae   20m
aclrule.netacl.flexibleengine.upbound.io/example-netacl-rule2   True    True     81fb312b-2441-4489-903b-b606d2d1f5ea   20m
aclrule.netacl.flexibleengine.upbound.io/example-netacl-rule4   True    True     a26c7d3f-35b1-46e6-9203-d72bec4b0da7   17m …
```

feat(netacl): Add network acl example

---

apis/cce/v1beta1/zz_generated.deepcopy.go
apis/cce/v1beta1/zz_generated.resolvers.go
apis/cce/v1beta1/zz_node_types.go
apis/cce/v1beta1/zz_nodepool_types.go
config/cce/config.go
package/crds/cce.flexibleengine.upbound.io_nodepools.yaml
package/crds/cce.flexibleengine.upbound.io_nodes.yaml

I have:
```
NAME                                                  READY   SYNCED   EXTERNAL-NAME                          AGE
node.cce.flexibleengine.upbound.io/example-cce-node   True    True    REDACTED   5m6s
NAME                                                        READY   SYNCED   EXTERNAL-NAME                          AGE
cluster.cce.flexibleengine.upbound.io/example-cce-cluster   True    True     REDACTED   27m
NAME                                                       READY   SYNCED   EXTERNAL-NAME                          AGE
nodepool.cce.flexibleengine.upbound.io/example-node-pool   True    True     REDACTED   27m
NAME                                                    READY   SYNCED   EXTERNAL-NAME     AGE
keypair.ecs.flexibleengine.upbound.io/example-keypair   True    True …
```

fix(cce): Add missing arguments in node/nodepool

---

apis/netacl/v1beta1/zz_acl_types.go
apis/netacl/v1beta1/zz_generated.deepcopy.go
apis/netacl/v1beta1/zz_generated.resolvers.go
apis/vpc/v1beta1/zz_generated.deepcopy.go
apis/vpc/v1beta1/zz_generated.resolvers.go
apis/vpc/v1beta1/zz_routetable_types.go
config/overrides.go
examples-generated/netacl/acl.yaml
examples/netacl/acl.yaml
package/crds/netacl.flexibleengine.upbound.io_acls.yaml
package/crds/vpc.flexibleengine.upbound.io_routetables.yaml

fix!: confusion argument Selector/Refs in netacl/acl and vpc/routetable

---

apis/css/v1beta1/zz_cluster_types.go
apis/css/v1beta1/zz_generated.deepcopy.go
apis/css/v1beta1/zz_generated.resolvers.go
config/css/config.go
examples/css/cluster.yaml
examples/css/snapshot.yaml
package/crds/css.flexibleengine.upbound.io_clusters.yaml

Fixes #119
I have:
Add exemple for  ressources cluster and snapshot from css
```
NAME                                                        READY   SYNCED   EXTERNAL-NAME  AGE
cluster.css.flexibleengine.upbound.io/example-css-cluster   True    True     REDACTED       86m
NAME                                                          READY   SYNCED   EXTERNAL-NAME   AGE
snapshot.css.flexibleengine.upbound.io/example-css-snapshot   True    True     REDACTED        11m
NAME                                                     READY   SYNCED   EXTERNAL-NAME   AGE
vpcsubnet.vpc.flexibleengine.upbound.io/example-subnet   True    True     REDACTED        86m
NAME                                                           READY   SYNCED   EXTERNAL-NAME  AGE …
```

feat(css):  Add examples cluster/snapshot

---

.vscode/extensions.json
.vscode/settings.json

- add recommended extensions vscode
- files associations

chore: add recommended extensions vscode and files associations

---

.github/workflows/release.yml

Add this section in future changelog : 
- Miscellaneous (chore)
- Dependencies (deps)
- Documentation (docs)

ci: add more sections in release changelog

---

config/provider.go

Add deprecated resources
Fixes #151
I have:

chore: add deprecated old resources

---

.github/PULL_REQUEST_TEMPLATE.md

chore: fix typo

---

package/crossplane.yaml

Add package annotations for marketplace

chore: add package annotations for marketplace
